<?php
session_start();
require_once 'config/database.php';

$error = "";
$success = "";
$rec_code_generated = "";

if (isset($_GET['success']) && $_GET['success'] == 1) {
    $success = "Your protocol has been successfully submitted! You will receive your official REC Code after staff screening.";
    $rec_code_generated = true;
}

if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['submit_author'])) {
    $title = trim($_POST['title']);
    $project_leader = trim($_POST['project_leader']);
    $author_email = trim($_POST['author_email']);
    $institution = trim($_POST['institution']);
    
    // Determine if Internal or External based on institution
    $protocol_type = (stripos($institution, 'Davao Del Norte State College') !== false || stripos($institution, 'DNSC') !== false) ? 'INT' : 'EXT';

    // Extracted author initials for the future REC code
    $name_parts = explode(',', $project_leader);
    $last_name = trim($name_parts[0]);
    $first_name = isset($name_parts[1]) ? trim($name_parts[1]) : '';
    $initials = "";
    if(!empty($last_name)) $initials .= strtoupper($last_name[0]);
    if(!empty($first_name)) $initials .= strtoupper($first_name[0]);
    if(empty($initials)) {
        $parts = explode(' ', $project_leader);
        foreach($parts as $p) if(!empty($p)) $initials .= strtoupper($p[0]);
    }
    $author_initials = substr($initials, 0, 3);

    if (empty($title) || empty($project_leader) || empty($author_email) || empty($institution)) {
        $error = "Please fill in all required fields.";
    } else {
        // No initial tracking code is generated. REC Code will be generated by staff.
        $tracking_code = null;
        
        // File Upload Handling (Multiple)
        $uploaded_files = [];
        $has_error = false;
        
        if (isset($_FILES['protocol_files'])) {
            $files = $_FILES['protocol_files'];
            $allowed = ['pdf'];

            for ($i = 0; $i < count($files['name']); $i++) {
                if ($files['error'][$i] == 0) {
                    $filename = $files['name'][$i];
                    $ext = strtolower(pathinfo($filename, PATHINFO_EXTENSION));
                    $filesize = $files['size'][$i];

                    if (!in_array($ext, $allowed)) {
                        $error = "Only PDF files are allowed ($filename).";
                        $has_error = true;
                        break;
                    } elseif ($filesize > 15 * 1024 * 1024) {
                        $error = "File size exceeds 15MB limit ($filename).";
                        $has_error = true;
                        break;
                    }
                    $uploaded_files[] = [
                        'tmp_name' => $files['tmp_name'][$i],
                        'name' => $filename
                    ];
                }
            }
        }

        if (empty($uploaded_files) && !$has_error) {
            $error = "Please upload at least one required document (PDF).";
            $has_error = true;
        }

        if (!$has_error) {
            try {
                $pdo->beginTransaction();

                // 1. Insert Protocol
                $stmt = $pdo->prepare("INSERT INTO protocols (rec_code, tracking_code, title, project_leader, author_email, institution, protocol_type, author_initials, review_type, status, created_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', 'submitted', NULL)");
                $stmt->execute([$tracking_code, $tracking_code, $title, $project_leader, $author_email, $institution, $protocol_type, $author_initials]);
                $protocol_id = $pdo->lastInsertId();

                if (!is_dir('uploads/protocols/')) { mkdir('uploads/protocols/', 0777, true); }

                foreach ($uploaded_files as $f) {
                    $newFilename = "REC_" . time() . "_" . $protocol_id . "_" . uniqid() . ".pdf";
                    if (move_uploaded_file($f['tmp_name'], "uploads/protocols/" . $newFilename)) {
                        $stmtF = $pdo->prepare("INSERT INTO protocol_files (protocol_id, file_name, file_path) VALUES (?, ?, ?)");
                        $stmtF->execute([$protocol_id, $f['name'], $newFilename]);
                    }
                }

                $stmtA = $pdo->prepare("INSERT INTO audit_logs (user_id, protocol_id, action) VALUES (NULL, ?, ?)");
                $stmtA->execute([$protocol_id, "Author submitted protocol online. Awaiting REC Code."]);

                $pdo->commit();

                // 4. Send Email Notification to Author
                require_once 'includes/notifications_helper.php';
                // Notify all active REC Staff
                $stmtS = $pdo->prepare("SELECT admin_id FROM admins WHERE role = 'rec_staff' AND status = 'active'");
                $stmtS->execute();
                $staffList = $stmtS->fetchAll(PDO::FETCH_ASSOC);
                foreach ($staffList as $s) {
                    notifyUser($pdo, $s['admin_id'], 'admin', 'New Protocol Submitted (Public Portal)', 
                        "A new protocol titled \"$title\" has been submitted via the public portal and requires screening.", 
                        "rec_staff/update_status?id=" . $protocol_id);
                }

                header("Location: submit_protocol?success=1");
                exit;

            } catch (Exception $e) {
                $pdo->rollBack();
                $error = "Error: " . $e->getMessage();
            }
        }
    }
}

include 'includes/header.php';
?>

<div style="background:#f1f5f9; min-height: 100vh; padding-bottom: 50px;">
    <!-- Public Header -->
    <nav class="navbar navbar-expand-lg bg-white border-bottom shadow-sm px-2 px-md-4 py-3">
        <div class="container-fluid align-items-center d-flex">
            <a href="index" class="d-flex align-items-center text-decoration-none">
                <img src="assets/images/logo.png" alt="DNSC" width="45" height="45" class="me-2 me-md-3">
                <div class="lh-1">
                    <h5 class="fw-bold text-navy mb-1 responsive-title" style="font-size: 16px;">DNSC REC</h5>
                    <span class="text-muted responsive-subtitle" style="font-size: 12px;">Research Ethics Committee</span>
                </div>
            </a>
            <div class="ms-auto d-flex gap-1">
                <a href="<?php echo BASE_URL; ?>track" class="btn btn-outline-navy btn-sm px-2 px-md-4 fw-bold shadow-sm rounded-pill btn-responsive-sm"><i class="fas fa-search me-1 me-md-2"></i> <span class="d-none d-sm-inline">Track </span>Submit</a>
            </div>
        </div>
    </nav>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-8 animate-up">
                
                <?php if ($rec_code_generated): ?>
                    <!-- Success State -->
                    <div class="card border-0 shadow-lg rounded-4 text-center p-5 mt-4">
                        <div class="mb-4">
                            <div class="d-inline-flex align-items-center justify-content-center bg-success-light text-success rounded-circle" style="width: 100px; height: 100px;">
                                <i class="fas fa-check fa-4x"></i>
                            </div>
                        </div>
                        <h2 class="fw-bold text-navy mb-3">Submission Complete!</h2>
                        <p class="text-muted mb-4 fs-5">Your research protocol has been successfully submitted to the DNSC Research Ethics Committee. Our staff will review your documents shortly.</p>
                        
                        <div class="alert alert-info border-0 rounded-4 mb-4 text-start p-4">
                            <h6 class="fw-bold"><i class="fas fa-info-circle me-2"></i> What happens next?</h6>
                            <p class="mb-0 small">Your submission is now queued for initial checking by the REC Secretariat. Once verified, you will receive an email containing your official <strong>REC Code</strong>. You will use that code to track your protocol's progress.</p>
                        </div>
                        
                        <div class="mt-4">
                            <a href="index" class="btn btn-navy px-5 py-3 rounded-pill shadow-sm fw-bold">Return to Home</a>
                        </div>
                    </div>
                <?php else: ?>
                    <!-- Submission Form -->
                    <div class="text-center mb-4">
                        <span class="badge bg-navy-light text-navy px-3 py-2 rounded-pill fw-bold text-uppercase tracking-wider mb-2">Committee Portal</span>
                        <h2 class="fw-bold text-navy mb-3">Submit a Research Protocol</h2>
                        <p class="text-muted fs-6" style="max-width: 600px; margin: 0 auto;">Welcome! Please fill out the core details of your research project and upload the full PDF protocol to request an ethical clearance.</p>
                    </div>

                    <div class="card border-0 shadow-lg rounded-4 overflow-hidden">
                        <div class="bg-navy p-4 text-white">
                            <h5 class="mb-0 fw-bold"><i class="fas fa-file-signature me-2"></i> Application Interface</h5>
                        </div>
                        <div class="card-body p-4 p-md-5">
                            <form action="submit_protocol" method="POST" enctype="multipart/form-data" id="submitForm">
                                <div class="mb-4">
                                    <label class="form-label fw-bold text-navy">Protocol Title <span class="text-danger">*</span></label>
                                    <textarea name="title" class="form-control" rows="3" placeholder="Enter the exact and full title of the research paper" required></textarea>
                                </div>

                                <div class="row mb-4">
                                    <div class="col-md-6">
                                        <label class="form-label fw-bold text-navy mb-1">Principal Investigator / Committee <span class="text-danger">*</span></label>
                                        <input type="text" name="project_leader" class="form-control" placeholder="e.g. Dela Cruz, Juan P." required>
                                        <small class="text-muted" style="font-size: 0.75rem;">Format: Last Name, First Name, Middle Name/Initial</small>
                                    </div>
                                    <div class="col-md-6 mt-4 mt-md-0">
                                        <label class="form-label fw-bold text-navy">Notification Email <span class="text-danger">*</span></label>
                                        <input type="email" name="author_email" class="form-control" placeholder="author@domain.com" required>
                                    </div>
                                </div>

                                <div class="row mb-4">
                                    <div class="col-md-6">
                                        <label class="form-label fw-bold text-navy">Affiliated Institution <span class="text-danger">*</span></label>
                                        <input type="text" name="institution" class="form-control" placeholder="e.g. Davao Del Norte State College" required>
                                    </div>
                                    <div class="col-md-6 mt-4 mt-md-0">
                                        <label class="form-label fw-bold text-navy">Project Type</label>
                                        <div class="p-2 border rounded-3 bg-light">
                                            <div class="form-check form-check-inline ms-2">
                                                <input class="form-check-input" type="radio" name="proj_type" id="typeInt" value="INT" checked>
                                                <label class="form-check-label small fw-bold" for="typeInt">Internal (DNSC)</label>
                                            </div>
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="radio" name="proj_type" id="typeExt" value="EXT">
                                                <label class="form-check-label small fw-bold" for="typeExt">External</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="mb-4">
                                    <label class="form-label fw-bold text-navy">Required Documents (PDF Only) <span class="text-danger">*</span></label>
                                    <div class="p-4 border rounded-3 bg-light position-relative">
                                        <input type="file" name="protocol_files[]" class="form-control mb-3" accept=".pdf" multiple required>
                                        <div class="small text-muted fw-bold mb-2 uppercase text-xs">Submission Checklist:</div>
                                        <ul class="small text-muted mb-0 ps-3">
                                            <li>Full Research Protocol / Methodology</li>
                                            <li>Informed Consent Forms (English & Local)</li>
                                            <li>Data Collection Instruments / Questionnaires</li>
                                            <li>Researcher Curriculum Vitae</li>
                                            <li>Letter of Request / Permission</li>
                                        </ul>
                                    </div>
                                    <small class="text-muted d-block mt-2"><i class="fas fa-info-circle me-1"></i> You can select multiple files at once. Ma'am Saddie will assign the review type based on these documents.</small>
                                </div>

                                <div class="alert bg-warning-light border-0 rounded-3 mb-4 d-flex align-items-start small p-3">
                                    <i class="fas fa-shield-alt text-warning mt-1 me-3 fa-lg"></i>
                                    <div class="text-dark">
                                        <strong>Data Privacy Notice:</strong> By submitting, you agree that your research data and personal information will be safely stored and processed exclusively for ethical reviews by REC committee members according to the Data Privacy Act.
                                    </div>
                                </div>

                                <button type="submit" name="submit_author" class="btn btn-navy py-3 w-100 fw-bold shadow-sm rounded-pill btn-lg">
                                    <i class="fas fa-paper-plane me-2"></i> Submit Protocol Request
                                </button>
                            </form>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<?php if ($error): ?>
    <script>
        Swal.fire({
            icon: 'error',
            title: 'Submission Error',
            text: '<?php echo $error; ?>',
            confirmButtonColor: '#1a2b4b'
        });
    </script>
<?php endif; ?>

<?php include 'includes/footer.php'; ?>

