<?php
require_once '../includes/auth_check.php';
checkAuth(['author']);
require_once '../config/database.php';

// Fetch author details to format name correctly (Last Name, First Name M.I.)
$stmtU = $pdo->prepare("SELECT * FROM users WHERE user_id = ?");
$stmtU->execute([$_SESSION['user_id']]);
$author_data = $stmtU->fetch();

$error = "";
$success = "";
$rec_code_generated = "";

if (isset($_GET['success']) && $_GET['success'] == 1) {
    $success = "Your protocol has been successfully submitted! You will receive your REC Code after screening.";
    $rec_code_generated = true;
}

// Auto-populate logged in user details
$author_id = $_SESSION['user_id'];
$author_name = $author_data['last_name'] . ', ' . $author_data['first_name'];
if (!empty($author_data['middle_initial'])) {
    $author_name .= ', ' . $author_data['middle_initial'];
}
$author_email_ses = $author_data['email'];

if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['submit_author'])) {
    $title = trim($_POST['title']);
    $project_leader = trim($_POST['project_leader']);
    $author_email = trim($_POST['author_email']);
    $institution = trim($_POST['institution']);
    
    // Determine if Internal or External based on institution
    $protocol_type = (stripos($institution, 'Davao Del Norte State College') !== false || stripos($institution, 'DNSC') !== false) ? 'INT' : 'EXT';

    // Extracted author initials for the future REC code (Requirement: First, Middle, Last)
    // Project leader format: "Last Name, First Name, Middle Name/Initial"
    $author_initials = "REF"; // fallback
    if (strpos($project_leader, ',') !== false) {
        $parts = explode(',', $project_leader);
        $ln = trim($parts[0]);
        $remaining = isset($parts[1]) ? trim($parts[1]) : '';
        
        $initials = "";
        // First Name initial
        if (!empty($remaining)) {
            $nameParts = explode(' ', $remaining);
            if (count($nameParts) > 0) $initials .= strtoupper($nameParts[0][0]);
            // Middle Name/Initial (if exists in the remaining part)
            if (count($nameParts) > 1) $initials .= strtoupper($nameParts[1][0]);
        }
        // Last Name initial
        if (!empty($ln)) $initials .= strtoupper($ln[0]);
        
        if (!empty($initials)) $author_initials = $initials;
    } else {
        // Fallback for non-comma names: just take first letters
        $parts = explode(' ', $project_leader);
        $initials = "";
        foreach($parts as $p) if(!empty($p)) $initials .= strtoupper($p[0]);
        $author_initials = substr($initials, 0, 3);
    }

    if (empty($title) || empty($project_leader) || empty($author_email) || empty($institution)) {
        $error = "Please fill in all required fields.";
    } else {
        // No initial tracking code is generated. REC Code will be generated by staff.
        $tracking_code = null;

        // Categorized File Upload Handling (Requirement I.1)
        $categories = ['Protocol', 'Consent', 'Questionnaire', 'CV', 'Letter', 'Endorsement'];
        $uploaded_files = [];
        $has_error = false;
        
        foreach ($categories as $cat) {
            $key = 'docs_' . strtolower($cat);
            if (isset($_FILES[$key]) && !empty($_FILES[$key]['name'][0])) {
                $files = $_FILES[$key];
                for ($i = 0; $i < count($files['name']); $i++) {
                    if ($files['error'][$i] == 0) {
                        $filename = $files['name'][$i];
                        $ext = strtolower(pathinfo($filename, PATHINFO_EXTENSION));
                        $filesize = $files['size'][$i];

                        if ($ext !== 'pdf') {
                            $error = "Only PDF files are allowed ($filename).";
                            $has_error = true; break 2;
                        } elseif ($filesize > 15 * 1024 * 1024) {
                            $error = "File size exceeds 15MB limit ($filename).";
                            $has_error = true; break 2;
                        }
                        $uploaded_files[] = [
                            'tmp_name' => $files['tmp_name'][$i],
                            'name' => $filename,
                            'type' => $cat
                        ];
                    }
                }
            }
        }

        if (empty($uploaded_files) && !$has_error) {
            $error = "Please upload at least your Research Protocol (PDF).";
            $has_error = true;
        }

        if (!$has_error) {
            try {
                $pdo->beginTransaction();

                // 1. Insert Protocol under this Author's user_id
                // Note: project_type is null by default, to be assigned by Staff (Step 2 Revision)
                $stmt = $pdo->prepare("INSERT INTO protocols (rec_code, tracking_code, title, project_leader, author_email, institution, protocol_type, author_initials, review_type, status, created_by) VALUES (?, ?, ?, ?, ?, ?, NULL, ?, 'pending', 'submitted', ?)");
                $stmt->execute([$tracking_code, $tracking_code, $title, $project_leader, $author_email, $institution, $author_initials, $author_id]);
                $protocol_id = $pdo->lastInsertId();

                if (!is_dir('../uploads/protocols/')) { mkdir('../uploads/protocols/', 0777, true); }

                foreach ($uploaded_files as $f) {
                    $newFilename = "REC_" . time() . "_" . $protocol_id . "_" . uniqid() . ".pdf";
                    if (move_uploaded_file($f['tmp_name'], "../uploads/protocols/" . $newFilename)) {
                        $stmtF = $pdo->prepare("INSERT INTO protocol_files (protocol_id, file_name, file_path, document_type) VALUES (?, ?, ?, ?)");
                        $stmtF->execute([$protocol_id, $f['name'], $newFilename, $f['type']]);
                    }
                }

                $stmtA = $pdo->prepare("INSERT INTO audit_logs (user_id, protocol_id, action) VALUES (?, ?, ?)");
                $stmtA->execute([$author_id, $protocol_id, "Author submitted protocol online. Awaiting REC Code."]);

                $pdo->commit();

                require_once '../includes/send_email.php';
                require_once '../includes/notifications_helper.php';
                $emailSubject = "Protocol Received - Awaiting REC Code";
                $emailBody = "<h2>Submission Successful</h2><p>Dear {$project_leader},</p><p>We have successfully received your research protocol: <strong>{$title}</strong>.</p><p>Your submission is currently undergoing initial screening. Once verified, you will be issued an official <strong>REC Code</strong> which you can use to track your protocol's progress.</p><br><p>Best regards,<br>DNSC REC Team</p>";
                sendEmailAPI($author_email, $project_leader, $emailSubject, $emailBody);

                notifyUser($pdo, $author_id, 'author', 'Protocol Submitted Successfully', 
                    "Your protocol has been successfully submitted and is awaiting staff screening.", 
                    "shared_view?id=" . $protocol_id);

                // Notify all active REC Staff (Requirement: Systematized Notifications)
                $stmtS = $pdo->prepare("SELECT admin_id FROM admins WHERE role = 'rec_staff' AND status = 'active'");
                $stmtS->execute();
                $staffList = $stmtS->fetchAll(PDO::FETCH_ASSOC);
                foreach ($staffList as $s) {
                    notifyUser($pdo, $s['admin_id'], 'admin', 'New Protocol Submitted', 
                        "A new protocol titled \"$title\" has been submitted and requires screening.", 
                        "rec_staff/update_status.php?id=" . $protocol_id);
                }

                header("Location: submit?success=1");
                exit;

            } catch (Exception $e) {
                $pdo->rollBack();
                $error = "Error: " . $e->getMessage();
            }
        }
    }
}

include '../includes/header.php';
?>

<div id="wrapper" class="dashboard-page d-flex">
    <?php include '../includes/sidebar.php'; ?>

    <div id="page-content-wrapper">
        <?php 
        $workspaceTitle = "New Protocol Submission";
        $workspaceSubtitle = "REC Ethics Review Application & Dossier Upload";
        include '../includes/topbar.php'; 
        ?>

        <div class="container-fluid p-4">
            
            <?php if ($rec_code_generated): ?>
                <div class="col-lg-8 mx-auto">
                    <div class="card border-0 shadow-lg rounded-4 text-center p-5 mt-4">
                        <div class="mb-4">
                            <div class="d-inline-flex align-items-center justify-content-center bg-success-light text-success rounded-circle" style="width: 100px; height: 100px;">
                                <i class="fas fa-check fa-4x"></i>
                            </div>
                        </div>
                        <h2 class="fw-bold text-navy mb-3">Submission Complete!</h2>
                        <p class="text-muted mb-4 fs-5">Your research protocol has been successfully submitted. You can now track its progress directly from your dashboard.</p>
                        
                        <div class="alert alert-info border-0 rounded-4 mb-4 text-start p-4">
                            <h6 class="fw-bold"><i class="fas fa-info-circle me-2"></i> What happens next?</h6>
                            <p class="mb-0 small">Your submission is now queued for initial checking by the REC Secretariat. Once verified, you will be assigned an official <strong>REC Code</strong>.</p>
                        </div>
                        
                        <div class="mt-4">
                            <a href="index" class="btn btn-navy px-5 py-3 rounded-pill shadow-sm fw-bold">Back to Dashboard</a>
                        </div>
                    </div>
                </div>
            <?php else: ?>
                <div class="col-lg-9 mx-auto">
                    <div class="mb-4">
                        <a href="index" class="text-decoration-none text-muted"><i class="fas fa-arrow-left me-2"></i> Back to Dashboard</a>
                        <h2 class="fw-bold text-navy mt-2">New Protocol Submission</h2>
                        <p class="text-muted">Fill out the required information and attach your protocol documents.</p>
                    </div>

                    <div class="card border-0 shadow-lg rounded-4 overflow-hidden">
                        <div class="bg-navy p-4 text-white">
                            <h5 class="mb-0 fw-bold"><i class="fas fa-file-signature me-2"></i> Application Interface</h5>
                        </div>
                        <div class="card-body p-4 p-md-5">
                            <form action="submit" method="POST" enctype="multipart/form-data">
                                <div class="mb-4">
                                    <label class="form-label fw-bold text-navy">Protocol Title <span class="text-danger">*</span></label>
                                    <textarea name="title" class="form-control" rows="3" placeholder="Enter the exact and full title of the research paper" required></textarea>
                                </div>

                                <div class="row mb-4">
                                    <div class="col-md-6">
                                        <label class="form-label fw-bold text-navy mb-1">Principal Investigator / Committee <span class="text-danger">*</span></label>
                                        <input type="text" name="project_leader" class="form-control" placeholder="e.g. Dela Cruz, Juan P." value="<?php echo htmlspecialchars($author_name); ?>" required>
                                        <small class="text-muted" style="font-size: 0.75rem;">Format: Last Name, First Name, Middle Name/Initial</small>
                                    </div>
                                    <div class="col-md-6 mt-4 mt-md-0">
                                        <label class="form-label fw-bold text-navy">Notification Email <span class="text-danger">*</span></label>
                                        <input type="email" name="author_email" class="form-control" placeholder="author@domain.com" value="<?php echo htmlspecialchars($author_email_ses); ?>" required>
                                    </div>
                                </div>

                                <div class="row mb-4">
                                    <div class="col-12">
                                        <label class="form-label fw-bold text-navy">Affiliated Institution <span class="text-danger">*</span></label>
                                        <input type="text" name="institution" class="form-control" placeholder="e.g. Davao Del Norte State College" required>
                                        <small class="text-muted small">Project Type (Internal/External) will be determined by REC Staff during screening.</small>
                                    </div>
                                </div>

                                <div class="mb-4">
                                    <h6 class="fw-bold text-navy mb-3"><i class="fas fa-folder-open me-2"></i>Submission Dossier (PDF Only)</h6>
                                    
                                    <div class="row g-3">
                                        <!-- Primary Slot: Protocol -->
                                        <div class="col-md-12">
                                            <div class="p-3 border rounded-3 bg-soft-navy">
                                                <label class="form-label fw-bold text-navy small mb-1">1. Research Protocol <span class="text-danger">*</span></label>
                                                <input type="file" name="docs_protocol[]" class="form-control form-control-sm" accept=".pdf" multiple required>
                                                <small class="x-small text-muted">Mandatory file</small>
                                            </div>
                                        </div>
                                        
                                        <!-- Secondary Slot: Consent -->
                                        <div class="col-md-6">
                                            <div class="p-3 border rounded-3 bg-light h-100">
                                                <label class="form-label fw-bold text-navy small mb-1">2. Informed Consent / Assent Consent</label>
                                                <input type="file" name="docs_consent[]" class="form-control form-control-sm" accept=".pdf" multiple>
                                                <small class="x-small text-muted">Multiple forms allowed</small>
                                            </div>
                                        </div>
                                        
                                        <!-- Third Slot: Questionnaire -->
                                        <div class="col-md-6">
                                            <div class="p-3 border rounded-3 bg-light h-100">
                                                <label class="form-label fw-bold text-navy small mb-1">3. Guide Questionnaire</label>
                                                <input type="file" name="docs_questionnaire[]" class="form-control form-control-sm" accept=".pdf" multiple>
                                                <small class="x-small text-muted">Questionnaires/Scales</small>
                                            </div>
                                        </div>
                                        
                                        <!-- Fourth Slot: CV -->
                                        <div class="col-md-6">
                                            <div class="p-3 border rounded-3 bg-light h-100">
                                                <label class="form-label fw-bold text-navy small mb-1">4. Curriculum Vitae</label>
                                                <input type="file" name="docs_cv[]" class="form-control form-control-sm" accept=".pdf" multiple>
                                                <small class="x-small text-muted">Curriculum Vitae of Researchers</small>
                                            </div>
                                        </div>
                                        
                                        <!-- Fifth Slot: Letter Request -->
                                        <div class="col-md-6">
                                            <div class="p-3 border rounded-3 bg-light h-100">
                                                <label class="form-label fw-bold text-navy small mb-1">5. Letter Request</label>
                                                <input type="file" name="docs_letter[]" class="form-control form-control-sm" accept=".pdf" multiple>
                                                <small class="x-small text-muted">Request letters, etc.</small>
                                            </div>
                                        </div>

                                        <!-- Sixth Slot: Endorsement -->
                                        <div class="col-md-6">
                                            <div class="p-3 border rounded-3 bg-light h-100">
                                                <label class="form-label fw-bold text-navy small mb-1">6. Endorsement</label>
                                                <input type="file" name="docs_endorsement[]" class="form-control form-control-sm" accept=".pdf" multiple>
                                                <small class="x-small text-muted">Endorsement letters</small>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="mt-3 p-3 border-start border-4 border-navy bg-light rounded-2">
                                        <small class="text-navy d-block mb-1 fw-bold"><i class="fas fa-info-circle me-1"></i> Multi-File Support</small>
                                        <small class="text-muted d-block small">You can choose multiple files per category by holding <strong>Ctrl/Shift</strong> during selection.</small>
                                    </div>
                                </div>

                                <button type="submit" name="submit_author" class="btn btn-navy py-3 w-100 fw-bold shadow-sm rounded-pill btn-lg">
                                    <i class="fas fa-paper-plane me-2"></i> Submit Protocol
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

        </div>
    </div>
</div>

<style>
.dashboard-page { background: #f8fafc; min-height: 100vh; }
</style>

<?php if ($error): ?>
    <script>Swal.fire({ icon: 'error', title: 'Submission Error', text: '<?php echo addslashes($error); ?>' });</script>
<?php endif; ?>

<?php include '../includes/footer.php'; ?>

